language: ruby
rvm:
  - 1.9.3
env:
  global:
    - secure: "MLwcHLj9um308gO3I0EGUiCR5yPylDdifFDPtUkvleaGs85bbMA/Yfy9Mn8tXXcs9fGMfoNBN1e+J5KkhENEnIXr5BKWMR6CfujxRDJB9fflAPEPz4mp0DuNIOlVj9NXiZBvyoHZIr9ZV2Ha4IPZUcQv1hzrn6DomZ5GVw3z/FM="
bundler_args: ''
script:
  - travis_retry cucumber install/install.feature
  - cucumber features
